- alias: "Another Visitor"
  trigger:
    platform: mqtt
    topic: "home/another_visitor"
  condition:
    - condition: state
      entity_id: input_boolean.doorbell_enabled
      state: "on"
  action:
    - service: notify.everyone
      data:
        title: "ANOTHER VISITOR!!!"
        message: "STAY A WHILE..."
    - service: shell_command.play_doorbell

- alias: "Custom Doorbell Greetings"
  trigger:
    platform: mqtt
    topic: "home/doorbell_greet"
  condition:
    - condition: state
      entity_id: input_boolean.motion_detection_alerts
      state: "on"
    - condition: state
      entity_id: input_boolean.doorbell_enabled
      state: "on"
  action:
    service: shell_command.play_sound
    data_template:
      filename: "{{trigger.payload}}"

- alias: "Motion detected"
  trigger:
    platform: mqtt
    topic: "home/frontdoor_movement"
    payload: "Yes"
  condition:
    - condition: time
      after: "21:00"
      before: "05:30"
    - condition: state
      entity_id: light.hue_color_lamp_7
      state: "off"
  action:
    - service: light.turn_on
      entity_id: light.hue_color_lamp_7
    - delay:
        minutes: 10
    - service: light.turn_off
      entity_id: light.hue_color_lamp_7
