
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

mqtt:
  broker: localhost

input_boolean:
  motion_detection_alerts:
    name: Enable/disable custom doorbell sounds
  doorbell_enabled:
    name: Enable/disable the doorbell

camera:
  - platform: mjpeg
    mjpeg_url: https://smell.today:8069/video_feed

shell_command:
  play_sound: "aplay /home/pi/nectalert/sounds/{{ filename }}"
  play_doorbell: aplay /home/pi/nectalert/sounds/doorbell.wav

notify:
  - name: everyone
    platform: group
    services:
      - service: mobile_app_nokia_7_plus
      - service: mobile_app_redmi_note_8

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
